del *.html
php 404.php >> 404.html
php bouraci_vrtaci_technika.php >> bouraci_vrtaci_technika.html
php cistici_technika-test.php >> cistici_technika-test.html
php cistici_technika.php >> cistici_technika.html
php elektrocentraly_kompresory.php >> elektrocentraly_kompresory.html
php hutnici_technika.php >> hutnici_technika.html
php import.php >> import.html
php index.php >> index.html
php laserova_technika.php >> laserova_technika.html
php nafukovaci_skakaci_hrad.php >> nafukovaci_skakaci_hrad.html
php naradi_stavba.php >> naradi_stavba.html
php navody.php >> navody.html
php obchodni_podminky.php >> obchodni_podminky.html
php ostatni.php >> ostatni.html
php prodej_servis.php >> prodej_servis.html
php rezaci_brousici_technika.php >> rezaci_brousici_technika.html
php sql.php >> sql.html
php svareci_technika.php >> svareci_technika.html
php zahradni_technika.php >> zahradni_technika.html